@startuml otaf.surrogate
!pragma useIntermediatePackages false

class otaf.surrogate._binary_threshold_classifier.BinaryClassificationModel {
  X_raw: None
  y_raw: None
  X: None
  X: None
  y: None
  clamping_threshold: None
  clamping: None
  finish_critertion_epoch: None
  loss_finish: None
  metric_finish: None
  train_size: None
  fc1: None
  fc2: None
  fc3: None
  model: None
  n_epochs: None
  batch_size: None
  criterion: None
  optimizer: None
  scheduler: None
  device: None
  noise_dims: None
  noise_level: None
  display_progress_disable: None
  history_loss: None
  history_metric: None
  best_loss: None
  best_metric: None
  best_weights: None
  save_path: None
}
class otaf.surrogate._neural_tolerancing_surrogate.DualNetworkPredictor {
  model_defects_to_gaps: None
  model_gap_def_to_slack: None
  X_def: None
  y_gap: None
  y_slack: None
  metric: None
  best_R2: None
  best_loss: None
  best_weights: None
  history_gaps: None
  history_slack: None
}
class otaf.surrogate._gaussian_surrogate_model.GaussianSurrogateModel {
  dimension: None
  bounds: None
  constraints: None
  min_val: None
  max_val: None
  X_train: None
  y_train: None
  gp: None
}
class otaf.surrogate._linear_solver_surrogate.LPNeuralSurrogateTolereancing {
  X_raw: None
  y_raw: None
  X: None
  y: None
  clamping: None
  finish_critertion_epoch: None
  loss_finish: None
  metric_finish: None
  compile_model: None
  train_size: None
  save_path: None
  input_description: None
  display_progress_disable: None
  metric: None
  criterion: None
  optimizer: None
  scheduler: None
  n_epochs: None
  batch_size: None
  batch_start: None
  best_metric: None
  best_loss: None
  best_weights: None
  history_loss: None
  history_metric: None
  noise_dims: None
  noise_level: None
  layer_eq: None
  layer_ub: None
  layer_XY: None
  layer_aydyx: None
  layer_x_rem: None
  layer_pred: None
  layer_act_y_h1: None
  layer_act_y_h2: None
}
class otaf.surrogate._loss_functions.LimitSpaceFocusedLoss {
  a: None
  b: None
  square: None
}
class otaf.surrogate._neural_surrogate.NeuralRegressorNetwork {
  X_raw: None
  y_raw: None
  X: None
  X: None
  y: None
  y: None
  clamping: None
  finish_critertion_epoch: None
  loss_finish: None
  metric_finish: None
  compile_model: None
  train_size: None
  save_path: None
  input_description: None
  display_progress_disable: None
  model: None
  metric: None
  loss_fn: None
  optimizer: None
  scheduler: None
  n_epochs: None
  batch_size: None
  batch_start: None
  best_metric: None
  best_loss: None
  best_weights: None
  history_loss: None
  history_metric: None
  noise_dims: None
  noise_level: None
}
class otaf.surrogate._loss_functions.PositiveLimitSpaceFocusedLoss {
  a: None
  b: None
  c: None
  square: None
}
footer Generated by //py2puml//
@enduml

