"""Custom exception classes for the OTAF project."""

from __future__ import annotations

__author__ = "Kramer84"
from ._exceptions import (
    ConflictingSurfaceDirectionsException,
    CylindricalInterferenceGeometricException,
    DuplicatePointError,
    GeometricConditionError,
    InvalidAffineTransformException,
    InvalidGlobalConstraintError,
    InvalidInteractionFormatError,
    InvalidPartLabelError,
    InvalidSurfaceDirectionError,
    InvalidSurfaceLabelError,
    LabelPatternError,
    LabelPrefixError,
    MissingKeyError,
    MissingOriginPointError,
    MissingSurfaceTypeKeyError,
    NoAxialOverlapException,
    NonConcentricCylindersException,
    NonUniqueCoordinatesError,
    NonUniqueLabelError,
    PartNotFoundError,
    PointDictionaryError,
    PointsNotOnPlaneError,
    SurfaceNotFoundError,
    UniqueLabelSuffixError,
    UnsupportedSurfaceTypeError,
    _raise_missing_dependency,
)
from ._timeout import timeout

__all__ = [
    "ConflictingSurfaceDirectionsException",
    "CylindricalInterferenceGeometricException",
    "DuplicatePointError",
    "GeometricConditionError",
    "InvalidAffineTransformException",
    "InvalidGlobalConstraintError",
    "InvalidInteractionFormatError",
    "InvalidPartLabelError",
    "InvalidSurfaceDirectionError",
    "InvalidSurfaceLabelError",
    "LabelPatternError",
    "LabelPrefixError",
    "MissingKeyError",
    "MissingOriginPointError",
    "MissingSurfaceTypeKeyError",
    "NoAxialOverlapException",
    "NonConcentricCylindersException",
    "NonUniqueCoordinatesError",
    "NonUniqueLabelError",
    "PartNotFoundError",
    "PointDictionaryError",
    "PointsNotOnPlaneError",
    "SurfaceNotFoundError",
    "UniqueLabelSuffixError",
    "UnsupportedSurfaceTypeError",
    "_raise_missing_dependency",
    "timeout",
]
