name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger the build from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-autodoc-typehints sphinx_rtd_theme myst-parser nbsphinx notebook
        pip install beartype numpy scipy sympy openturns pandas torch matplotlib tqdm joblib trimesh gldpy

    - name: Convert README.md to README.rst
      run: |
        pandoc README.md -f markdown -t rst -o docs/source/README.rst

    # Step 4: Build the documentation
    - name: Build documentation
      run: |
        cd docs
        make clean
        make html

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
